/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `daftarresep`;
CREATE TABLE `daftarresep` (
  `id_daftar` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `asal` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `bahan` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `langkah` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `foto` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id_daftar`),
  UNIQUE KEY `daftarresep_foto_unique` (`foto`),
  KEY `daftarresep_user_id_foreign` (`user_id`),
  CONSTRAINT `daftarresep_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `akun` (`id_akun`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `daftarresep` (`id_daftar`, `nama`, `asal`, `bahan`, `langkah`, `foto`, `user_id`, `created_at`, `updated_at`) VALUES
(1, 'Gudeg Solo', 'Jawa Tengah', '-Nangka muda\r\n-Santan\r\n-Telur rebus\r\n-Ayam\r\n-Bawang merah\r\n-Bawang putih\r\n-Kemiri\r\n-Ketumbar\r\n-Lengkuas\r\n-Daun salam\r\n-Daun jati (untuk pewarna)\r\n-Gula merah\r\n-Garam', '1.Rebus potongan nangka muda hingga empuk, tambahkan air secukupnya.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, kemiri, ketumbar, lengkuas, daun salam) hingga harum.\r\n3.Masukkan daun jati, gula merah, garam, santan, dan air rebusan nangka, aduk rata.\r\n4.Masak hingga bumbu meresap dan kuah mengental.\r\n5.Sajikan gudeg dengan telur rebus dan ayam.', 'img/resepku/1717551661.jpg', 2, '2024-06-05 01:41:01', '2024-06-05 01:41:01');
INSERT INTO `daftarresep` (`id_daftar`, `nama`, `asal`, `bahan`, `langkah`, `foto`, `user_id`, `created_at`, `updated_at`) VALUES
(2, 'Es Dawet Ireng', 'Jawa Tengah', '-Tepung beras\r\n-Tepung sagu\r\n-Air\r\n-Daun pandan (untuk aroma)\r\n-Pewarna alami (biasanya daun suji atau abu merang)\r\n-Santan\r\n-Gula merah\r\n-Garam\r\n-Es batu', '1.Campur tepung beras, tepung sagu, air, dan daun pandan yang sudah dihaluskan, aduk hingga rata.\r\n2.Tambahkan pewarna alami (biasanya dari daun suji atau abu merang), aduk kembali.\r\n3.Masak adonan hingga mengental, kemudian dinginkan.\r\n4.Sajikan es dawet dengan santan, gula merah cair, dan es batu.', 'img/resepku/1717551766.jpeg', 2, '2024-06-05 01:42:46', '2024-06-05 01:42:46');
INSERT INTO `daftarresep` (`id_daftar`, `nama`, `asal`, `bahan`, `langkah`, `foto`, `user_id`, `created_at`, `updated_at`) VALUES
(3, 'Ayam Penyet', 'Jawa Tengah', '-Ayam\r\n-Tepung terigu\r\n-Tepung tapioka\r\n-Bawang putih\r\n-Ketumbar\r\n-Garam\r\n-Merica\r\n-Minyak goreng\r\n-Sambal terasi', '1.Lumuri potongan ayam dengan campuran tepung terigu, tepung tapioka, bawang putih, ketumbar, garam, dan merica.\r\n2.Goreng ayam hingga kecokelatan dan matang.\r\n3.Sajikan ayam penyet dengan sambal terasi dan nasi hangat.', 'img/resepku/1717553565.jpg', 2, '2024-06-05 02:12:45', '2024-06-05 02:12:45');
INSERT INTO `daftarresep` (`id_daftar`, `nama`, `asal`, `bahan`, `langkah`, `foto`, `user_id`, `created_at`, `updated_at`) VALUES
(4, 'Tempe Mendoan', 'Jawa Tengah', '-Tempe\r\n-Tepung terigu\r\n-Tepung beras\r\n-Bawang putih\r\n-Ketumbar\r\n-Garam\r\n-Daun bawang\r\n-Air\r\n-Minyak goreng', '1.Potong tempe menjadi irisan tipis.\r\n2.Campur tepung terigu, tepung beras, bawang putih, ketumbar, garam, dan daun bawang yang sudah diiris tipis.\r\n3.Balur irisan tempe dengan adonan tepung, goreng hingga kecokelatan.\r\n4.Sajikan tempe mendoan dengan sambal kecap atau sambal petis.', 'img/resepku/1717555177.jpg', 2, '2024-06-05 02:39:37', '2024-06-05 02:39:37'),
(5, 'Garang Asem', 'Jawa Tengah', '-Ayam kampung\r\n-Belimbing wuluh\r\n-Tomat\r\n-Cabe rawit\r\n-Daun salam\r\n-Daun jeruk\r\n-Serai\r\n-Lengkuas\r\n-Bawang merah\r\n-Bawang putih\r\n-Garam\r\n-Gula\r\n-Santan\r\n-Daun pisang (untuk membungkus)', '1.Rebus potongan ayam hingga empuk, tiriskan.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, cabe rawit, lengkuas, jahe, kunyit) hingga harum.\r\n3.Masukkan belimbing wuluh, tomat, daun salam, daun jeruk, serai, lengkuas, dan bumbu lainnya, aduk rata.\r\n4.Masukkan ayam, tambahkan air secukupnya, garam, dan gula, masak hingga bumbu meresap dan kuah mengental.', 'img/resepku/1717555259.jpg', 2, '2024-06-05 02:40:59', '2024-06-05 02:40:59'),
(6, 'Bakmi Jawa', 'Jawa Tengah', '-Mie kuning\r\n-Ayam kampung\r\n-Telur\r\n-Tauge\r\n-Kol\r\n-Daun bawang\r\n-Bawang merah\r\n-Bawang putih\r\n-Merica\r\n-Kecap manis\r\n-Garam\r\n-Kaldu ayam', 'Mie kuning\r\nAyam kampung\r\nTelur\r\nTauge\r\nKol\r\nDaun bawang\r\nBawang merah\r\nBawang putih\r\nMerica\r\nKecap manis\r\nGaram\r\nKaldu ayam', 'img/resepku/1717556126.jpg', 2, '2024-06-05 02:55:26', '2024-06-05 02:55:26'),
(7, 'Buntil', 'Jawa Tengah', '-Daun pepaya\r\n-Kelapa parut\r\n-Teri\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabe merah\r\n-Garam\r\n-Gula merah\r\n-Santan', '1.Ambil selembar daun pepaya, letakkan kelapa parut dan teri di atasnya.\r\n2.Tambahkan bumbu halus (bawang merah, bawang putih, cabe merah) yang sudah ditumis hingga harum.\r\n3.Bungkus bahan dengan daun pepaya, kukus hingga matang.\r\n4.Sajikan buntil dengan nasi hangat.', 'img/resepku/1717556167.jpg', 2, '2024-06-05 02:56:07', '2024-06-05 02:56:07'),
(8, 'Tahu Aci Tegal', 'Jawa Tengah', '-Tahu\r\n-Tepung kanji\r\n-Bawang putih\r\n-Daun kucai\r\n-Garam\r\n-Merica\r\n-Air\r\n-Minyak goreng', '1.Campur tahu yang sudah dipotong kecil dengan adonan tepung kanji, bawang putih, daun kucai, garam, merica, dan air.\r\n2.Goreng tahu hingga matang dan kecokelatan.\r\n3.Sajikan tahu aci dengan sambal kecap atau sambal terasi.', 'img/resepku/1717556233.jpg', 2, '2024-06-05 02:57:13', '2024-06-05 02:57:13'),
(9, 'Nasi Grombyang', 'Jawa Tengah', '-Daging sapi\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Kemiri\r\n-Ketumbar\r\n-Merica\r\n-Jahe\r\n-Lengkuas\r\n-Daun salam\r\n-Serai\r\n-Daun jeruk\r\n-Kecap manis\r\n-Garam\r\n-Gula', '1.Rebus daging sapi hingga empuk, tiriskan.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, kemiri, ketumbar, merica, jahe, lengkuas) hingga harum.\r\n3.Masukkan daun salam, serai, daun jeruk, kecap manis, garam, gula, santan, dan air, masak hingga mendidih.\r\n4.Sajikan nasi grombyang dengan daging sapi dan kuahnya.', 'img/resepku/1717556326.jpg', 2, '2024-06-05 02:58:46', '2024-06-05 02:58:46'),
(10, 'Gethuk Magelang', 'Jawa Tengah', '-Singkong\r\n-Gula pasir\r\n-Kelapa parut\r\n-Vanili\r\n-Garam', '1.Kukus singkong hingga lunak, lalu haluskan.\r\n2.Campur singkong halus dengan gula pasir, kelapa parut, vanili, dan sedikit garam, aduk hingga rata.\r\n3.Bentuk adonan menjadi bulat-bulat kecil, sajikan sebagai kudapan.', 'img/resepku/1717556368.jpg', 2, '2024-06-05 02:59:28', '2024-06-05 02:59:28'),
(11, 'Roti Buaya', 'DKI Jakarta', '-Tepung terigu\r\n-Gula pasir\r\n-Ragi instan\r\n-Telur\r\n-Susu cair\r\n-Garam\r\n-Margarin', '1.Campur tepung terigu, gula pasir, dan ragi instan.\r\n2.Tambahkan telur dan susu cair, uleni hingga kalis.\r\n3.Masukkan garam dan margarin, uleni hingga elastis.\r\n4.Diamkan adonan selama 1 jam hingga mengembang.\r\n5.Bentuk adonan menjadi bentuk buaya.\r\n6.Panggang dalam oven dengan suhu 180°C selama 30-40 menit hingga matang.\r\n7.Dinginkan sebelum disajikan.', 'img/resepku/1717557379.jpeg', 2, '2024-06-05 03:16:19', '2024-06-05 03:16:19'),
(12, 'Es Selendang Mayang', 'DKI Jakarta', '-Tepung hunkwe\r\n-Tepung beras\r\n-Gula pasir\r\n-Daun pandan\r\n-Santan\r\n-Garam\r\n-Sirup merah\r\n-Air', '1.Campur tepung hunkwe, tepung beras, gula pasir, dan air, aduk rata.\r\n2.Masak hingga mengental, tambahkan daun pandan, angkat.\r\n3.Tuang adonan dalam loyang, biarkan dingin dan mengeras.\r\n4.Potong-potong sesuai selera.\r\n5.Sajikan dengan sirup merah, santan, dan es batu.', 'img/resepku/1717557456.jpeg', 2, '2024-06-05 03:17:36', '2024-06-05 03:17:36'),
(13, 'Sayur Asem Betawi', 'DKI Jakarta', '-Labu siam\r\n-Melinjo\r\n-Kacang panjang\r\n-Jagung manis\r\n-Daun melinjo\r\n-Asam jawa\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabai merah\r\n-Lengkuas\r\n-Daun salam\r\n-Gula merah\r\n-Garam\r\n-Air', '1.Rebus air hingga mendidih.\r\n2.Masukkan bawang merah, bawang putih, cabai merah, lengkuas, dan daun salam, masak hingga harum.\r\n3.Tambahkan labu siam, melinjo, kacang panjang, dan jagung manis, masak hingga sayuran matang.\r\n4.Tambahkan daun melinjo dan asam jawa, garam, dan gula merah, aduk rata.\r\n5.Sajikan panas.', 'img/resepku/1717557515.jpeg', 2, '2024-06-05 03:18:35', '2024-06-05 03:18:35'),
(14, 'Pecak Gurame', 'DKI Jakarta', '-Ikan gurame\r\n-Jeruk nipis\r\n-Bawang putih\r\n-Bawang merah\r\n-Cabai rawit\r\n-Cabai merah keriting\r\n-Tomat\r\n-Kencur\r\n-Daun kemangi\r\n-Garam\r\n-Gula\r\n-Minyak goreng', '1.Lumuri ikan gurame dengan air jeruk nipis, garam, dan diamkan selama 15 menit.\r\n2.Goreng ikan hingga matang dan kecokelatan, tiriskan.\r\n3.Haluskan bawang putih, bawang merah, cabai rawit, cabai merah keriting, tomat, dan kencur.\r\n4.Tambahkan garam dan gula, aduk rata.\r\n5.Siram bumbu di atas ikan gurame yang telah digoreng.\r\n6.Sajikan dengan daun kemangi.', 'img/resepku/1717557590.jpeg', 2, '2024-06-05 03:19:50', '2024-06-05 03:19:50'),
(15, 'Rujak Juhi', 'DKI Jakarta', '-Juhi (ikan asin)\r\n-Kangkung\r\n-Kol\r\n-Tauge\r\n-Kentang\r\n-Timun\r\n-Kacang tanah\r\n-Gula merah\r\n-Cabai merah\r\n-Bawang putih\r\n-Air asam jawa\r\n-Garam\r\n-Air', '1.Rebus juhi, kangkung, kol, tauge, dan kentang, tiriskan.\r\n2.Iris juhi dan campur dengan sayuran dalam mangkuk.\r\n3.Haluskan kacang tanah, gula merah, cabai merah, bawang putih, air asam jawa, garam, dan air.\r\n4.Siram bumbu di atas sayuran dan juhi.\r\n5.Sajikan dengan kerupuk', 'img/resepku/1717558516.jpeg', 2, '2024-06-05 03:35:16', '2024-06-05 03:35:16');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;