/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP TABLE IF EXISTS `resep`;
CREATE TABLE `resep` (
  `id_resep` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `asal` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `bahan` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `langkah` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `foto` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `jumlah_simpan` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id_resep`),
  UNIQUE KEY `resep_foto_unique` (`foto`),
  KEY `resep_user_id_foreign` (`user_id`),
  CONSTRAINT `resep_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `akun` (`id_akun`)
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `resep` (`id_resep`, `nama`, `asal`, `bahan`, `langkah`, `foto`, `user_id`, `jumlah_simpan`, `created_at`, `updated_at`) VALUES
(2, 'Soto Bandung', 'Jawa Barat', '-Daging sapi\r\n-Lobak\r\n-Daun bawang\r\n-Daun seledri\r\n-Bawang putih\r\n-Bawang merah\r\n-Jahe\r\n-Lengkuas\r\n-Serai\r\n-Daun salam\r\n-Garam\r\n-Merica\r\n-Kaldu sapi\r\n-Jeruk nipis\r\n-Sambal (opsional)', '1.Rebus daging sapi hingga empuk, angkat, dan potong-potong.Sisihkan kaldu rebusan.\r\n2.Tumis bawang putih, bawang merah, jahe, lengkuas, serai, dan daun salam hingga harum.\r\n3.Masukkan tumisan bumbu ke dalam kaldu rebusan daging.\r\n4.Tambahkan lobak yang sudah dipotong-potong dan masak hingga lobak empuk.\r\n5.Tambahkan garam dan merica sesuai selera.\r\n6.Sajikan soto dengan potongan daging, daun bawang, seledri, dan perasan jeruk nipis. Tambahkan sambal jika suka.', 'img/resepku/1716799076.jpeg', 2, 0, '2024-05-27 08:37:56', '2024-06-16 14:57:34');
INSERT INTO `resep` (`id_resep`, `nama`, `asal`, `bahan`, `langkah`, `foto`, `user_id`, `jumlah_simpan`, `created_at`, `updated_at`) VALUES
(3, 'Nasi Tutug Oncom', 'Jawa Barat', '-Nasi putih\r\n-Oncom\r\n-Bawang merah\r\n-Bawang putih\r\n-Kencur\r\n-Daun kemangi\r\n-Garam\r\n-Minyak goreng', '1.Haluskan bawang merah, bawang putih, dan kencur.\r\n2.Tumis bumbu halus hingga harum, lalu masukkan oncom yang sudah dihancurkan.\r\n3.Tambahkan garam sesuai selera dan masak hingga oncom matang.\r\n4.Campurkan oncom dengan nasi putih, aduk rata.\r\n5.Tambahkan daun kemangi dan aduk hingga rata.\r\n6.Sajikan nasi tutug oncom dengan lauk pendamping sesuai selera.', 'img/resepku/1716806806.jpg', 1, 0, '2024-05-27 10:46:46', '2024-05-27 10:46:46');
INSERT INTO `resep` (`id_resep`, `nama`, `asal`, `bahan`, `langkah`, `foto`, `user_id`, `jumlah_simpan`, `created_at`, `updated_at`) VALUES
(4, 'Batagor', 'Jawa Barat', '-Ikan tenggiri\r\n-Tepung sagu\r\n-Tahu putih\r\n-Kulit pangsit\r\n-Telur\r\n-Garam\r\n-Merica\r\n-Bawang putih\r\n-Kacang tanah (untuk saus kacang)\r\n-Cabe merah\r\n-Gula merah\r\n-Air asam jawa\r\n-Kecap manis', '1.Haluskan ikan tenggiri, campurkan dengan tepung sagu, bawang putih halus, garam, dan merica.\r\n2.Potong tahu menjadi beberapa bagian dan keruk sebagian isinya, isi dengan adonan ikan.\r\n3.Bungkus sebagian adonan dengan kulit pangsit.\r\n4.Goreng tahu dan pangsit yang sudah diisi hingga matang dan kecokelatan.\r\n5.Untuk saus kacang, haluskan kacang tanah, cabe merah, bawang putih, gula merah, dan air asam jawa, lalu masak hingga mengental.\r\n6.Sajikan batagor dengan saus kacang dan kecap manis.', 'img/resepku/1716806967.jpg', 1, 0, '2024-05-27 10:49:27', '2024-05-27 10:49:27');
INSERT INTO `resep` (`id_resep`, `nama`, `asal`, `bahan`, `langkah`, `foto`, `user_id`, `jumlah_simpan`, `created_at`, `updated_at`) VALUES
(5, 'Siomay Bandung', 'Jawa Barat', '-Ikan tenggiri\r\n-Tepung sagu\r\n-Telur\r\n-Bawang putih\r\n-Garam\r\n-Merica\r\n-Kulit pangsit\r\n-Tahu\r\n-Pare\r\n-Kol\r\n-Telur rebus\r\n-Kentang\r\n-Kacang tanah (untuk saus kacang)\r\n-Cabe merah\r\n-Gula merah\r\n-Air asam jawa\r\n-Kecap manis', '1.Haluskan ikan tenggiri, campurkan dengan tepung sagu, telur, bawang putih halus, garam, dan merica.\r\n2.Isi tahu, pare, kol, dan kulit pangsit dengan adonan ikan.\r\n3.Kukus tahu, pare, kol, kulit pangsit, telur rebus, dan kentang hingga matang.\r\n4.Untuk saus kacang, haluskan kacang tanah, cabe merah, bawang putih, gula merah, dan air asam jawa, lalu masak hingga mengental.\r\n5.Sajikan siomay dengan saus kacang dan kecap manis.', 'img/resepku/1716807062.jpg', 1, 0, '2024-05-27 10:51:02', '2024-05-27 10:51:02'),
(6, 'Pepes Ikan', 'Jawa Barat', '-Ikan (biasanya ikan mas atau ikan kembung)\r\n-Daun kemangi\r\n-Daun bawang\r\n-Tomat\r\n-Serai\r\n-Daun salam\r\n-Daun jeruk\r\n-Cabe rawit\r\n-Cabe merah\r\n-Bawang merah\r\n-Bawang putih\r\n-Kunyit\r\n-Jahe\r\n-Garam\r\n-Gula\r\n-Daun pisang (untuk -membungkus)', '1.Haluskan bawang merah, bawang putih, cabe merah, kunyit, jahe, dan garam.\r\n2.Lumuri ikan dengan bumbu halus dan tambahkan daun kemangi, daun bawang, tomat, serai, daun salam, daun jeruk, dan cabe rawit.\r\n3.Bungkus ikan dengan daun pisang dan sematkan dengan tusuk gigi.\r\n4.Kukus pepes ikan hingga matang.\r\n5.Bakar sebentar di atas api agar aromanya keluar lebih harum.\r\n6.Sajikan pepes ikan hangat.', 'img/resepku/1716807265.jpg', 1, 0, '2024-05-27 10:54:25', '2024-05-27 10:54:25'),
(7, 'Combro', 'Jawa Barat', '-Singkong parut\r\n-Kelapa parut\r\n-Oncom\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabe rawit\r\n-Daun bawang\r\n-Garam\r\n-Minyak goreng', '1.Tumis bawang merah, bawang putih, dan cabe rawit hingga harum, lalu masukkan oncom yang sudah dihancurkan.\r\n2.Tambahkan garam dan daun bawang, masak hingga matang.\r\n3.Campurkan singkong parut dengan kelapa parut dan garam.\r\n4.Ambil sedikit adonan singkong, pipihkan, isi dengan tumisan oncom, lalu bentuk bulat.\r\n5.Goreng combro hingga kecokelatan.\r\n6.Sajikan combro hangat.', 'img/resepku/1716807316.jpg', 1, 0, '2024-05-27 10:55:16', '2024-06-16 14:56:52'),
(8, 'Surabi', 'Jawa Barat', '-Tepung beras\r\n-Santan\r\n-Kelapa parut\r\n-Garam\r\n-Gula merah (untuk sirup)', '1.Campurkan tepung beras dengan santan dan garam hingga menjadi adonan yang kental.\r\n2.Panaskan cetakan surabi, olesi dengan sedikit minyak.\r\n3.Tuang adonan surabi ke dalam cetakan dan masak hingga matang.\r\n4.Untuk sirup gula merah, rebus gula merah dengan sedikit air hingga larut dan mengental.\r\n5.Sajikan surabi dengan sirup gula merah.', 'img/resepku/1716807374.jpg', 1, 0, '2024-05-27 10:56:14', '2024-05-27 10:56:14'),
(9, 'Karedok', 'Jawa Barat', '-Kacang panjang\r\n-Tauge\r\n-Terong\r\n-Timun\r\n-Kol\r\n-Kemangi\r\n-Bumbu kacang \r\nterdiri dari:\r\n-kacang tanah\r\n-cabe merah\r\n-bawang putih\r\n-gula merah\r\n-garam\r\n-air asam jawa', '1.Potong semua sayuran menjadi ukuran kecil.\r\n2.Untuk bumbu kacang, haluskan kacang tanah, cabe merah, bawang putih, gula merah, garam, dan air asam jawa.\r\n3.Campurkan sayuran dengan bumbu kacang hingga rata.\r\n4.Sajikan karedok segar.', 'img/resepku/1716807536.jpg', 1, 0, '2024-05-27 10:58:56', '2024-05-27 10:58:56'),
(10, 'Lotek', 'Jawa Barat', '-Kangkung\r\n-Bayam\r\n-Tauge\r\n-Kacang panjang\r\n-Timun\r\n-Kol\r\n-Bumbu kacang \r\nterdiri dari :\r\n-kacang tanah\r\n-cabe merah\r\n-bawang putih\r\n-gula merah\r\n-garam\r\n-air asam jawa', '1.Rebus kangkung, bayam, tauge, dan kacang panjang hingga matang.\r\n2.Potong timun dan kol.\r\n3.Untuk bumbu kacang, haluskan kacang tanah, cabe merah, bawang putih, gula merah, garam, dan air asam jawa.\r\n4.Campurkan semua sayuran dengan bumbu kacang hingga rata.\r\n5.Sajikan lotek segar.', 'img/resepku/1716807726.jpg', 1, 0, '2024-05-27 11:02:06', '2024-05-27 11:02:06'),
(11, 'Mie Kocok Bandung', 'Jawa Barat', '-Mie kuning\r\n-Daging sapi\r\n-Kikil sapi\r\n-Tauge\r\n-Daun bawang\r\n-Daun seledri\r\n-Bawang goreng\r\n-Bawang putih\r\n-Bawang merah\r\n-Jahe\r\n-Garam\r\n-Merica\r\n-Kaldu sapi\r\n-Jeruk nipis\r\n-Sambal (opsional)', '1.Rebus daging sapi dan kikil hingga empuk, angkat, dan potong-potong. Sisihkan kaldu rebusan.\r\n2.Tumis bawang putih, bawang merah, dan jahe hingga harum.\r\n3.Masukkan tumisan bumbu ke dalam kaldu rebusan daging.\r\n4.Tambahkan garam dan merica sesuai selera.\r\n5.Rebus mie kuning dan tauge hingga matang.\r\n6.Sajikan mie dalam mangkuk, tambahkan potongan daging, kikil, daun bawang, seledri, dan bawang goreng. Siram dengan kuah kaldu.\r\n7.Tambahkan perasan jeruk nipis dan sambal jika suka', 'img/resepku/1716807889.jpg', 1, 0, '2024-05-27 11:04:49', '2024-05-27 11:04:49'),
(12, 'Nasi Liwet Solo', 'Jawa Tengah', '-Beras\r\n-Santan\r\n-Serai\r\n-Daun salam\r\n-Daun pandan\r\n-Garam\r\n-Ayam kampung\r\n-Telur rebus\r\n-Tahu\r\n-Tempe\r\n-Kecap manis\r\n-Bawang merah\r\n-Bawang putih\r\n-Kemiri\r\n-Ketumbar\r\n-Jahe\r\n-Lengkuas\r\n-Daun jeruk\r\n-Daun bawang', '1.Cuci beras hingga bersih, kemudian masak dengan santan, serai, daun salam, dan daun pandan hingga matang.\r\n2.Potong-potong ayam kampung, rebus dalam air hingga empuk, tambahkan sedikit garam.\r\n3.Rebus telur hingga matang, kupas.\r\n4.Potong tahu dan tempe menjadi beberapa bagian, goreng hingga keemasan.\r\n5.Tumis bawang merah dan bawang putih hingga harum, tambahkan ketumbar, kemiri, jahe, dan lengkuas yang sudah dihaluskan. Tumis hingga bumbu matang.\r\n6.Masukkan daun jeruk dan daun bawang, aduk sebentar, lalu masukkan ke dalam nasi liwet yang sudah matang.\r\n7.Sajikan nasi liwet dengan ayam, telur, tahu, tempe, dan kecap manis.', 'img/resepku/1716808214.jpg', 1, 0, '2024-05-27 11:10:14', '2024-05-27 11:10:14'),
(13, 'Lumpia Semarang', 'Jawa Tengah', '-Kulit lumpia\r\n-Rebung (bambu muda)\r\n-Ayam cincang\r\n-Udang cincang\r\n-Telur\r\n-Bawang putih\r\n-Bawang merah\r\n-Merica\r\n-Gula\r\n-Garam\r\n-Kecap manis\r\n-Minyak goreng\r\n-Saus (untuk pelengkap)', '1.Siapkan kulit lumpia, lalu isi dengan adonan rebung, ayam cincang, udang cincang, dan telur yang sudah diolah.\r\n2.Gulung kulit lumpia dan sematkan ujungnya dengan air agar tidak terbuka saat digoreng.\r\n3.Goreng lumpia hingga keemasan, tiriskan.\r\n4.Sajikan lumpia panas dengan saus sebagai pelengkap.', 'img/resepku/1716808293.jpg', 1, 0, '2024-05-27 11:11:33', '2024-05-27 11:11:33'),
(14, 'Wingko Babat', 'Jawa Tengah', '-Tepung ketan\r\n-Kelapa parut\r\n-Gula pasir\r\n-Garam\r\n-Vanili\r\n-Santan', '1.Campur tepung ketan, kelapa parut, gula pasir, garam, vanili, dan santan hingga tercampur rata.\r\n2.Panaskan wajan datar, tuang adonan tepung, ratakan.\r\n3.Panggang adonan hingga matang dan kecokelatan, angkat dan dinginkan.\r\n4.Potong-potong wingko babat sesuai selera, sajikan sebagai kudapan.', 'img/resepku/1716808343.jpg', 1, 0, '2024-05-27 11:12:23', '2024-05-27 11:12:23'),
(15, 'Tahu Gimbal', 'Jawa Tengah', '-Tahu\r\n-Udang\r\n-Tepung terigu\r\n-Tauge\r\n-Kol\r\n-Telur\r\n-Kacang tanah\r\n-Bawang putih\r\n-Cabe merah\r\n-Gula merah\r\n-Garam\r\n-Air asam jawa\r\n-Petis\r\n-Minyak goreng', '1.Potong tahu menjadi beberapa bagian, goreng hingga kecokelatan.\r\n2.Goreng udang hingga matang, angkat dan tiriskan.\r\n3.Buat adonan basah dengan mencampurkan tepung terigu dengan air hingga kental.\r\n4.Tumis bawang putih, cabe merah, dan gula merah hingga harum.\r\n5.Masukkan tahu, udang, dan tauge ke dalam tumisan, tambahkan air asam jawa, garam, dan petis. Aduk rata hingga bumbu meresap.\r\n6.Sajikan tahu gimbal dengan bumbu dan taburan kacang tanah.', 'img/resepku/1716808405.jpg', 1, 0, '2024-05-27 11:13:25', '2024-05-27 11:13:25'),
(16, 'Serabi Notosuman', 'Jawa Tengah', '-Tepung beras\r\n-Santan\r\n-Kelapa parut\r\n-Garam\r\n-Gula pasir\r\n-Daun pandan (untuk aroma)\r\n-Ragi', '1.Campur tepung beras, santan, kelapa parut, garam, dan gula pasir hingga menjadi adonan yang kental.\r\n2.Tambahkan daun pandan yang sudah dihaluskan untuk aroma.\r\n3.Diamkan adonan selama beberapa jam hingga mengembang.\r\n4.Panaskan cetakan serabi, tuang adonan hingga penuh, tutup dan biarkan hingga matang.\r\n5.Sajikan serabi notosuman dengan taburan kelapa parut dan gula pasir.', 'img/resepku/1716808589.jpg', 1, 0, '2024-05-27 11:16:29', '2024-05-27 11:16:29'),
(17, 'Mangut Beong', 'Jawa Tengah', 'Ikan beong (atau ikan lele)\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabe merah\r\n-Cabe rawit\r\n-Lengkuas\r\n-Jahe\r\n-Kunyit\r\n-Daun salam\r\n-Daun jeruk\r\n-Serai\r\n-Tomat\r\n-Garam\r\n-Gula', '1.Haluskan bumbu (bawang merah, bawang putih, cabe merah, lengkuas, jahe, kunyit).\r\n2.Tumis bumbu halus hingga harum, masukkan ikan beong yang sudah dibersihkan.\r\n3.Tuangkan santan, tambahkan daun salam, daun jeruk, garam, dan gula secukupnya.\r\n4.Masak hingga ikan matang dan bumbu meresap.\r\n5.Sajikan mangut beong dengan nasi hangat.', 'img/resepku/1716808618.jpg', 1, 0, '2024-05-27 11:16:58', '2024-05-27 11:16:58'),
(18, 'Bandeng Presto', 'Jawa Tengah', '-Ikan bandeng\r\n-Bawang putih\r\n-Kunyit\r\n-Garam\r\n-Daun pisang (untuk membungkus)\r\n-Air\r\n-Minyak goreng', '1.Bersihkan ikan bandeng, lumuri dengan garam dan kunyit, diamkan beberapa saat.\r\n2.Masukkan ikan ke dalam panci presto, tambahkan bumbu halus (bawang putih, kunyit, garam), air secukupnya, masak dalam panci presto hingga matang.\r\n3.Angkat ikan bandeng, dinginkan, lalu goreng hingga kecokelatan.\r\n4.Sajikan bandeng presto dengan nasi hangat dan sambal terasi.', 'img/resepku/1716808662.jpg', 1, 0, '2024-05-27 11:17:42', '2024-05-27 11:17:42'),
(19, 'Mie Kopyok', 'Jawa Tengah', '-Mie kuning\r\n-Tauge\r\n-Tahu pong\r\n-Lontong\r\n-Kucai\r\n-Bawang merah goreng\r\n-Kecap manis\r\n-Bawang putih\r\n-Cabe rawit\r\n-Garam\r\n-Air\r\n-Minyak goreng', '1.Rebus mie kuning hingga matang, tiriskan.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, cabe rawit) hingga harum.\r\n3.Masukkan tauge, tahu pong, lontong, mie kuning, bawang merah goreng, kecap manis, bawang putih, cabe rawit, garam, air, dan minyak goreng, aduk rata.\r\n4.Sajikan mie kopyok panas dengan taburan bawang merah goreng.', 'img/resepku/1716808707.jpg', 1, 0, '2024-05-27 11:18:27', '2024-05-27 11:18:27'),
(20, 'Nasi Gandul Pati', 'Jawa Tengah', '-Daging sapi\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Kemiri\r\n-Ketumbar\r\n-Merica\r\n-Jahe\r\n-Lengkuas\r\n-Daun salam\r\n-Serai\r\n-Daun jeruk\r\n-Kecap manis\r\n-Garam\r\n-Gula', '1.Rebus daging sapi hingga empuk, tiriskan.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, kemiri, ketumbar, merica, jahe, lengkuas) hingga harum.\r\n3.Masukkan daun salam, serai, daun jeruk, kecap manis, garam, gula, santan, dan air, masak hingga mendidih.\r\n4.Sajikan nasi gandul dengan daging sapi dan kuahnya.', 'img/resepku/1716808769.jpg', 1, 0, '2024-05-27 11:19:29', '2024-05-27 11:19:29'),
(21, 'Soto Kudus', 'Jawa Tengah', '-Daging ayam\r\n-Tauge\r\n-Daun seledri\r\n-Bawang putih\r\n-Bawang merah\r\n-Jahe\r\n-Kunyit\r\n-Lengkuas\r\n-Serai\r\n-Daun salam\r\n-Garam\r\n-Merica\r\n-Kaldu ayam\r\n-Bawang goreng\r\n-Jeruk nipis', '1.Rebus daging ayam hingga empuk, tiriskan.\r\n2.Tumis bumbu halus (bawang putih, bawang merah, jahe, kunyit, lengkuas, serai, daun salam) hingga harum.\r\n3.Masukkan kaldu ayam, garam, merica, dan gula, masak hingga mendidih.\r\n4.Sajikan soto dengan tauge, daun seledri, bawang goreng, dan jeruk nipis.', 'img/resepku/1716808807.jpg', 1, 0, '2024-05-27 11:20:07', '2024-05-27 11:20:07'),
(22, 'Kerak Telor', 'DKI Jakarta', '-Beras ketan putih\r\n-Telur bebek\r\n-Ebi\r\n-Kelapa parut kasar\r\n-Bawang goreng\r\n-Garam\r\n-Merica bubuk\r\n-Minyak goreng', '1.Panaskan wajan kecil, tambahkan sedikit minyak.\r\n2.Masukkan beras ketan, tekan-tekan hingga padat.\r\n3.Kocok telur bebek, garam, dan merica, tuangkan di atas ketan.\r\n4.Taburi ebi dan kelapa parut sangrai.\r\n5.Tutup wajan, masak hingga matang.\r\n6.Sajikan dengan bawang goreng.', 'img/resepku/1716808883.jpeg', 1, 0, '2024-05-27 11:21:23', '2024-05-27 11:21:23'),
(23, 'Soto Betawi', 'DKI Jakarta', '-Daging sapi (dada, sandung lamur)\r\n-Santan\r\n-Air\r\n-Serai\r\n-Daun jeruk\r\n-Daun salam\r\n-Kentang\r\n-Tomat\r\n-Minyak goreng\r\n-Bawang merah\r\n-Bawang putih\r\n-Kemiri\r\n-Ketumbar\r\n-Jinten\r\n-Lada butir\r\n-Kunyit\r\n-Jahe', '1.Rebus daging sapi hingga empuk, potong-potong.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, kemiri, ketumbar, jinten, lada, kunyit, jahe) hingga harum.\r\n3.Masukkan serai, daun jeruk, dan daun salam, aduk rata.\r\n4.Tambahkan daging sapi, aduk rata.\r\n5.Tuang air, masak hingga mendidih.\r\n6.Tambahkan kentang, masak hingga empuk.\r\n7.Tuang santan, masak hingga mendidih sambil terus diaduk.\r\n8.Tambahkan garam dan gula secukupnya.\r\n9.Sajikan dengan potongan tomat dan bawang goreng.', 'img/resepku/1716808939.jpeg', 1, 0, '2024-05-27 11:22:19', '2024-05-27 11:22:19'),
(24, 'Nasi Uduk Betawi', 'DKI Jakarta', '-Beras\r\n-Santan\r\n-Serai\r\n-Daun salam\r\n-Daun pandan\r\n-Garam', '1.Kukus beras setengah matang.\r\n2.Rebus santan dengan serai, daun salam, daun pandan, dan garam hingga mendidih.\r\n3.Masukkan beras kukus ke dalam santan, aduk hingga santan meresap.\r\n4.Kukus kembali beras hingga matang.\r\n5.Sajikan dengan lauk-pauk seperti ayam goreng, tempe, dan telur dadar', 'img/resepku/1716808979.jpeg', 1, 0, '2024-05-27 11:22:59', '2024-05-27 11:22:59'),
(25, 'Asinan Betawi', 'DKI Jakarta', '-Tauge\r\n-Kol\r\n-Sawi asin\r\n-Timun\r\n-Tahu putih\r\n-Cabai merah besar\r\n-Cabai merah keriting\r\n-Kacang tanah\r\n-Ebi\r\n-Gula merah\r\n-Garam\r\n-Cuka\r\n-Air', '1.Rebus tauge, kol, dan sawi asin sebentar, tiriskan.\r\n2.Campur semua bahan sayuran dalam mangkuk besar.\r\n3.Haluskan bumbu (cabai merah besar, cabai merah keriting, kacang tanah, ebi, gula merah, garam).\r\n4.Tambahkan cuka dan air, aduk rata.\r\n5.Siram bumbu di atas sayuran.\r\n6.Sajikan dengan kerupuk dan kacang tanah goreng.', 'img/resepku/1716809040.jpeg', 1, 0, '2024-05-27 11:24:00', '2024-05-27 11:24:00'),
(26, 'Semur Jengkol', 'DKI Jakarta', '-Jengkol\r\n-Bawang merah\r\n-Daun salam\r\n-Serai\r\n-Lengkuas\r\n-Kecap manis\r\n-Minyak goreng\r\n-Air\r\n-Bawang merah\r\n-Bawang putih\r\n-Kemiri\r\n-Merica butir\r\n-Ketumbar\r\n-Jahe', '1.Rebus jengkol hingga empuk, memarkan.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, kemiri, merica, ketumbar, jahe) hingga harum.\r\n3.Masukkan daun salam, serai, dan lengkuas, aduk rata.\r\n4.Tambahkan jengkol, aduk hingga rata.\r\n5.Tuang air, kecap manis, garam, dan gula, masak hingga kuah mengental dan meresap.\r\n6.Sajikan dengan nasi putih.', 'img/resepku/1716809093.jpeg', 1, 0, '2024-05-27 11:24:53', '2024-05-27 11:24:53'),
(27, 'Gado-Gado Betawi', 'DKI Jakarta', '-Kangkung\r\n-Bayam\r\n-Tauge\r\n-Kacang panjang\r\n-Kentang\r\n-Timun\r\n-Tahu putih\r\n-Telur rebus\r\n-Kerupuk udang\r\n-Lontong\r\n-Kacang tanah\r\n-Bawang putih\r\n-Cabai merah keriting\r\n-Cabai rawit merah\r\n-Daun jeruk\r\n-Gula merah\r\n-Air asam jawa\r\n-Garam\r\n-Air', '1.Rebus kangkung, bayam, tauge, dan kacang panjang, tiriskan.\r\n2.Goreng tahu hingga kecokelatan, potong-potong.\r\n3.Haluskan bumbu kacang (kacang tanah, bawang putih, cabai merah, cabai rawit, daun jeruk, gula merah, air asam jawa, garam).\r\n4.Tambahkan air matang secukupnya hingga mencapai kekentalan yang diinginkan.\r\n5.Campur semua sayuran, tahu, dan lontong dalam mangkuk.\r\n6.Siram dengan bumbu kacang, aduk rata.\r\n7.Sajikan dengan kerupuk udang dan telur rebus.', 'img/resepku/1716809166.jpeg', 1, 0, '2024-05-27 11:26:06', '2024-05-27 11:26:06'),
(28, 'Ketoprak', 'DKI Jakarta', '-Bihun\r\n-Tauge\r\n-Tahu putih\r\n-Lontong\r\n-Bawang putih\r\n-Cabai rawit\r\n-Kacang tanah\r\n-Kecap manis\r\n-Air asam jawa\r\n-Gula merah\r\n-Garam\r\n-Air', '1.Rebus bihun dan tauge hingga matang, tiriskan.\r\n2.Goreng tahu hingga kecokelatan, potong-potong.\r\n3.Haluskan bumbu (bawang putih, cabai rawit, kacang tanah, kecap manis, air asam jawa, gula merah, garam).\r\n4.Campur bihun, tauge, tahu, dan lontong dalam mangkuk.\r\n5.Siram dengan bumbu, aduk rata.\r\n6.Sajikan dengan taburan bawang goreng dan kerupuk.', 'img/resepku/1716809210.jpeg', 1, 0, '2024-05-27 11:26:50', '2024-05-27 11:26:50'),
(29, 'Sate Betawi', 'DKI Jakarta', '-Daging sapi\r\n-Bawang merah\r\n-Bawang putih\r\n-Ketumbar\r\n-Merica\r\n-Garam\r\n-Gula merah\r\n-Kecap manis\r\n-Minyak goreng\r\n-Air asam jawa', '1.Potong daging sapi, tusuk dengan tusukan sate.\r\n2.Haluskan bumbu (bawang merah, bawang putih, ketumbar, merica, garam, gula merah).\r\n3.Campur bumbu halus dengan kecap manis dan minyak goreng.\r\n4.Rendam daging dalam bumbu, diamkan selama 1 jam.\r\n5.Bakar sate hingga matang sambil diolesi bumbu.\r\n6.Sajikan dengan sambal kacang atau kecap manis.', 'img/resepku/1716809257.jpeg', 1, 0, '2024-05-27 11:27:38', '2024-05-27 11:27:38'),
(30, 'Laksa Betawi', 'DKI Jakarta', '-Ayam\r\n-Santan\r\n-Mie kuning\r\n-Daun kemangi\r\n-Tauge\r\n-Serai\r\n-Daun salam\r\n-Daun jeruk\r\n-Lengkuas\r\n-Bawang merah\r\n-Bawang putih\r\n-Kemiri\r\n-Ketumbar\r\n-Jinten\r\n-Lada butir\r\n-Kunyit\r\n-Jahe\r\n-Garam\r\n-Gula', '1.Rebus ayam hingga matang, suwir-suwir.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, kemiri, ketumbar, jinten, lada, kunyit, jahe) hingga harum.\r\n3.Masukkan serai, daun salam, daun jeruk, dan lengkuas, aduk rata.\r\n4.Tambahkan santan dan air, masak hingga mendidih.\r\n5.Masukkan mie kuning, ayam suwir, dan tauge, masak hingga matang.\r\n6.Sajikan dengan daun kemangi dan bawang goreng.', 'img/resepku/1716809311.jpeg', 1, 0, '2024-05-27 11:28:31', '2024-05-27 11:28:31'),
(31, 'Nasi Kebuli', 'DKI Jakarta', '-Beras basmati\r\n-Daging kambing\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Tomat\r\n-Cengkih\r\n-Kayu manis\r\n-Kapulaga\r\n-Kismis\r\n-Garam\r\n-Minyak samin', '1.Tumis bumbu halus (bawang merah, bawang putih, tomat) hingga harum.\r\n2.Masukkan daging kambing, aduk hingga berubah warna.\r\n3.Tambahkan santan, cengkih, kayu manis, kapulaga, garam, dan kismis, masak hingga daging empuk.\r\n4.Masukkan beras basmati, aduk rata.\r\n5.Masak hingga beras matang dan santan meresap.\r\n6.Sajikan dengan acar dan emping.', 'img/resepku/1716809358.jpeg', 1, 0, '2024-05-27 11:29:18', '2024-05-27 11:29:18'),
(32, 'Ayam Bekakak', 'Banten', '-Ayam kampung\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Ketumbar\r\n-Kemiri\r\n-Kunyit\r\n-Serai\r\n-Daun salam\r\n-Garam\r\n-Gula merah', '1.Haluskan bawang merah, bawang putih, ketumbar, kemiri, kunyit, dan garam.\r\n2.Tumis bumbu halus hingga harum.\r\n3.Tambahkan santan, daun salam, dan serai, masak hingga mendidih.\r\n4.Masukkan ayam, masak hingga matang dan santan mengental.\r\n5.Panggang ayam hingga kecokelatan.\r\n6.Sajikan ayam bekakak dengan sambal dan lalapan.', 'img/resepku/1716809410.jpeg', 1, 0, '2024-05-27 11:30:10', '2024-05-27 11:30:10'),
(33, 'Sate Bebek', 'Banten', '-Daging bebek\r\n-Bawang merah\r\n-Bawang putih\r\n-Ketumbar\r\n-Kemiri\r\n-Merica\r\n-Kecap manis\r\n-Garam\r\n-Gula merah', '1.Potong daging bebek sesuai selera.\r\n2.Haluskan bawang merah, bawang putih, ketumbar, kemiri, merica, kecap manis, dan garam.\r\n3.Rendam potongan daging bebek dalam bumbu halus selama 1 jam.\r\n4.Tusuk daging bebek dengan tusukan sate.\r\n5.Bakar sate bebek hingga matang.\r\n6.Sajikan dengan sambal kecap dan lontong.', 'img/resepku/1716809455.jpeg', 1, 0, '2024-05-27 11:30:55', '2024-05-27 11:30:55'),
(34, 'Gecom', 'Banten', '-Tempe\r\n-Tauge\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabai merah\r\n-Kecap manis\r\n-Garam\r\n-Gula merah\r\n-Asam jawa', '1.Potong tempe sesuai selera dan goreng setengah matang.\r\n2.Tumis bawang merah, bawang putih, dan cabai merah hingga harum.\r\n3.Tambahkan kecap manis, garam, gula merah, dan air asam jawa.\r\n4.Masukkan tempe dan tauge, aduk rata.\r\n5.Masak hingga bumbu meresap.\r\n6.Sajikan gecom dengan nasi hangat.', 'img/resepku/1716809508.jpeg', 1, 0, '2024-05-27 11:31:48', '2024-05-27 11:31:48'),
(35, 'Laksa Tangerang', 'Banten', '-Bihun\r\n-Daging ayam\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Kemiri\r\n-Ketumbar\r\n-Jintan\r\n-Serai\r\n-Daun salam\r\n-Daun jeruk\r\n-Garam\r\n-Gula merah', '1.Rebus bihun hingga matang, tiriskan.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, kemiri, ketumbar, jintan) hingga harum.\r\n3.Masukkan serai, daun salam, dan daun jeruk, aduk rata.\r\n4.Tambahkan potongan daging ayam, masak hingga berubah warna.\r\n5.Tuang santan, masak hingga mendidih.\r\n6.Sajikan laksa dengan bihun, telur rebus, dan daun kemangi.', 'img/resepku/1716809555.jpeg', 1, 0, '2024-05-27 11:32:35', '2024-05-27 11:32:35'),
(36, 'Sate Bandeng', 'Banten', '-Ikan bandeng\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Ketumbar\r\n-Kemiri\r\n-Merica\r\n-Kunyit\r\n-Gula merah\r\n-Garam\r\n-Daun pisang', '1.Bersihkan ikan bandeng, ambil dagingnya, dan buang tulangnya.\r\n2.Haluskan daging ikan bersama santan, bawang merah, bawang putih, ketumbar, kemiri, merica, kunyit, gula merah, dan garam.\r\n3.Bungkus adonan daging ikan dengan daun pisang, tusuk dengan tusukan sate.\r\n4.Bakar di atas arang hingga matang dan harum.\r\n5.Sajikan dengan sambal kecap.', 'img/resepku/1716809672.jpeg', 1, 0, '2024-05-27 11:34:32', '2024-05-27 11:34:32'),
(37, 'Nasi Sumsum', 'Banten', '-Beras\r\n-Tulang sumsum sapi\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Daun salam\r\n-Serai\r\n-Garam\r\n-Daun jeruk', '1.Cuci bersih beras dan rendam selama 30 menit.\r\n2.Rebus tulang sumsum sapi hingga empuk, angkat dan sisihkan sumsum dari tulangnya.\r\n3.Tumis bawang merah dan bawang putih hingga harum.\r\n4.Masukkan sumsum, santan, daun salam, serai, daun jeruk, dan garam. Masak hingga mendidih.\r\n5.Masukkan beras, aduk hingga meresap dan beras matang.\r\n6.Sajikan nasi sumsum dengan pelengkap.', 'img/resepku/1716809708.jpeg', 1, 0, '2024-05-27 11:35:08', '2024-05-27 11:35:08'),
(38, 'Rabeg Kambing', 'Banten', '-Daging kambing\r\n-Jeroan kambing\r\n-Bawang merah\r\n-Bawang putih\r\n-Ketumbar\r\n-Merica\r\n-Jahe\r\n-Lengkuas\r\n-Daun salam\r\n-Serai\r\n-Daun jeruk\r\n-Kecap manis\r\n-Garam\r\n-Gula', '1.Potong daging dan jeroan kambing sesuai selera.\r\n2.Tumis bawang merah, bawang putih, ketumbar, merica, jahe, dan lengkuas hingga harum.\r\n3.Masukkan daun salam, serai, dan daun jeruk, aduk rata.\r\n4.Tambahkan daging kambing, aduk hingga berubah warna.\r\n5.Tuang air dan kecap manis, masak hingga daging empuk.\r\n6.Tambahkan garam dan gula, aduk rata.\r\n7.Sajikan rabeg kambing dengan nasi putih.', 'img/resepku/1716809759.jpeg', 1, 0, '2024-05-27 11:35:59', '2024-05-27 11:35:59'),
(39, 'Kue Pasung', 'Banten', '-Tepung beras\r\n-Tepung sagu\r\n-Gula merah\r\n-Santan\r\n-Daun pandan\r\n-Garam\r\n-Air', '1.Campur tepung beras dan tepung sagu dengan air, aduk rata.\r\n2.Masak santan, gula merah, daun pandan, dan garam hingga mendidih.\r\n3.Tuang campuran santan ke dalam adonan tepung, aduk hingga mengental.\r\n4.Tuang adonan ke dalam cetakan daun pisang.\r\n5.Kukus hingga matang.\r\n6.Sajikan kue pasung dalam keadaan hangat.', 'img/resepku/1716809803.jpeg', 1, 0, '2024-05-27 11:36:43', '2024-05-27 11:36:43'),
(40, 'Emping Menes', 'Banten', '-Melinjo\r\n-Garam\r\n-Minyak goreng', '1.Kupas melinjo dan cuci bersih.\r\n2.Rebus melinjo hingga empuk, tiriskan.\r\n3.Tumbuk melinjo hingga pipih.\r\n4.Jemur emping melinjo hingga kering.\r\n5.Goreng emping hingga matang dan renyah.\r\n6.Taburi garam sesuai selera', 'img/resepku/1716809854.jpeg', 1, 0, '2024-05-27 11:37:34', '2024-05-27 11:37:34'),
(41, 'Ketan Bintul', 'Banten', '-Beras ketan\r\n-Santan\r\n-Daun pandan\r\n-Garam\r\n-Kacang tanah\r\n-Gula merah', '1.Kukus beras ketan hingga setengah matang.\r\n2.Campur santan, daun pandan, dan garam, masak hingga mendidih.\r\n3.Masukkan ketan ke dalam campuran santan, aduk hingga meresap.\r\n4.Kukus kembali ketan hingga matang.\r\n5.Taburi ketan dengan kacang tanah yang telah dihaluskan dan gula merah.\r\n6.Sajikan ketan bintul dalam keadaan hangat.', 'img/resepku/1716809899.jpeg', 1, 0, '2024-05-27 11:38:19', '2024-05-27 11:38:19'),
(42, 'Gudeg Jogja', 'DI Yogyakarta', '-Nangka muda\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Ketumbar\r\n-Kemiri\r\n-Lengkuas\r\n-Daun salam\r\n-Daun jati\r\n-Gula merah\r\n-Garam', '1.Potong nangka muda, cuci bersih.\r\n2.Haluskan bawang merah, bawang putih, ketumbar, dan kemiri.\r\n3.Tumis bumbu halus hingga harum.\r\n4.Masukkan nangka muda, lengkuas, daun salam, daun jati, gula merah, dan garam.\r\n5.Tambahkan santan, masak dengan api kecil hingga meresap dan kering.\r\n6.Sajikan dengan nasi dan krecek.', 'img/resepku/1716809968.jpeg', 1, 0, '2024-05-27 11:39:28', '2024-05-27 11:39:28'),
(43, 'Sate Klatak', 'DI Yogyakarta', '-Daging kambing\r\n-Bawang putih\r\n-Bawang merah\r\n-Ketumbar\r\n-Merica\r\n-Garam\r\n-Kecap manis', '1.Potong daging kambing menjadi dadu.\r\n2.Haluskan bawang putih, bawang merah, ketumbar, dan merica.\r\n3.Lumuri daging dengan bumbu halus dan garam, diamkan selama 1 jam.\r\n4.Tusuk daging dengan tusuk sate, bakar hingga matang.\r\n5.Sajikan dengan kecap manis.', 'img/resepku/1716810013.jpeg', 1, 0, '2024-05-27 11:40:13', '2024-05-27 11:40:13'),
(44, 'Bakpia Pathok', 'DI Yogyakarta', '-Tepung terigu\r\n-Gula\r\n-Minyak goreng\r\n-Ragi\r\n-Kacang hijau\r\n-Santan', '1.Campur tepung terigu, gula, ragi, dan minyak goreng, uleni hingga kalis.\r\n2.Rendam kacang hijau, kukus hingga matang, haluskan.\r\n3.Campur kacang hijau dengan santan dan gula, masak hingga kental.\r\n4.Ambil sedikit adonan, pipihkan, isi dengan kacang hijau, bentuk bulat.\r\n5.Panggang hingga matang dan kecokelatan.', 'img/resepku/1716810055.jpeg', 1, 0, '2024-05-27 11:40:55', '2024-05-27 11:40:55'),
(45, 'Wedang Uwuh', 'DI Yogyakarta', '-Daun pala\r\n-Jahe\r\n-Kayu secang\r\n-Daun cengkeh\r\n-Gula batu', '1.Rebus jahe, daun pala, kayu secang, dan daun cengkeh hingga mendidih.\r\n2.Tambahkan gula batu, aduk hingga larut.\r\n3.Sajikan wedang uwuh selagi hangat.', 'img/resepku/1716810092.jpeg', 1, 0, '2024-05-27 11:41:32', '2024-05-27 11:41:32'),
(46, 'Gatot Gunung Kidul', 'DI Yogyakarta', '-Singkong (gaplek)\r\n-Kelapa parut\r\n-Gula merah\r\n-Garam', '1.Rendam gaplek hingga lunak, potong-potong.\r\n2.Kukus gaplek hingga matang.\r\n3.Campur kelapa parut dengan sedikit garam.\r\n4.Sajikan gaplek dengan taburan kelapa parut dan gula merah cair.', 'img/resepku/1716810137.jpeg', 1, 0, '2024-05-27 11:42:17', '2024-05-27 11:42:17'),
(47, 'Kipo Kotagede', 'DI Yogyakarta', '-Tepung ketan\r\n-Gula merah\r\n-Kelapa parut\r\n-Daun pandan\r\n-Santan', '1.Campur tepung ketan dengan santan hingga kalis.\r\n2.Buat isian dari gula merah dan kelapa parut, masak hingga kental.\r\n3.Ambil sedikit adonan, pipihkan, isi dengan gula merah, bentuk bulat.\r\n4.Bungkus dengan daun pandan, kukus hingga matang.', 'img/resepku/1716810167.jpeg', 1, 0, '2024-05-27 11:42:47', '2024-05-27 11:42:47'),
(48, 'Soto Kadipiro', 'DI Yogyakarta', '-Daging ayam\r\n-Bawang putih\r\n-Bawang merah\r\n-Kemiri\r\n-Serai\r\n-Daun salam\r\n-Daun jeruk\r\n-Santan\r\n-Garam\r\n-Merica', '1.Rebus ayam hingga matang, suwir dagingnya.\r\n2.Tumis bumbu halus, serai, daun salam, dan daun jeruk hingga harum.\r\n3.Masukkan santan, aduk hingga mendidih.\r\n4.Tambahkan ayam suwir, garam, dan merica, masak hingga meresap.\r\n5.Sajikan soto dengan pelengkap seperti bawang goreng dan sambal.', 'img/resepku/1716810211.jpg', 1, 0, '2024-05-27 11:43:31', '2024-05-27 11:43:31'),
(49, 'Oseng-Oseng Mercon', 'DI Yogyakarta', '-Daging sapi\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabai rawit\r\n-Cabai merah\r\n-Kecap manis\r\n-Garam\r\n-Gula merah', '1.Potong daging sapi sesuai selera.\r\n2.Haluskan bawang merah, bawang putih, cabai rawit, dan cabai merah.\r\n3.Tumis bumbu halus hingga harum.\r\n4.Masukkan daging, tambahkan kecap manis, garam, dan gula merah.\r\n5.Masak hingga daging empuk dan bumbu meresap.\r\n6.Sajikan oseng-oseng mercon dengan nasi hangat.', 'img/resepku/1716810246.jpg', 1, 0, '2024-05-27 11:44:06', '2024-05-27 11:44:06'),
(50, 'Mangut Lele', 'DI Yogyakarta', '-Ikan lele\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabai merah\r\n-Daun salam\r\n-Serai\r\n-Lengkuas\r\n-Garam', '1.Goreng ikan lele hingga matang, sisihkan.\r\n2.Haluskan bawang merah, bawang putih, dan cabai merah.\r\n3.Tumis bumbu halus, daun salam, serai, dan lengkuas hingga harum.\r\n4.Tambahkan santan, masak hingga mendidih.\r\n5.Masukkan lele, tambahkan garam, masak hingga bumbu meresap.\r\n6.Sajikan mangut lele dengan nasi hangat.', 'img/resepku/1716810279.jpeg', 1, 0, '2024-05-27 11:44:39', '2024-05-27 11:44:39'),
(51, 'Tiwul Gunung Kidul', 'DI Yogyakarta', '-Singkong (gaplek)\r\n-Kelapa parut\r\n-Gula merah\r\n-Garam', '1.Rendam gaplek hingga lunak, potong-potong.\r\n2.Kukus gaplek hingga matang.\r\n3.Campur kelapa parut dengan sedikit garam.\r\n4.Sajikan gaplek dengan taburan kelapa parut dan gula merah cair.', 'img/resepku/1716810311.jpeg', 1, 0, '2024-05-27 11:45:11', '2024-05-27 11:45:11'),
(52, 'Rawon', 'Jawa Timur', '-Daging sapi (sandung lamur atau iga sapi)\r\n-Bawang merah\r\n-Bawang putih\r\n-Keluak\r\n-Kunyit\r\n-Jahe\r\n-Kemiri\r\n-Ketumbar\r\n-Jintan\r\n-Merica\r\n-Cabai merah besar -(opsional)\r\n-Serai\r\n-Daun jeruk\r\n-Daun salam\r\n-Lengkuas\r\n-Garam\r\n-Gula\r\n-Minyak goreng\r\n-Tauge\r\n-Daun bawang\r\n-Daun seledri\r\n-Telur asin\r\n-Kerupuk udang\r\n-Sambal terasi\r\n-Jeruk nipis', '1.Rebus daging sapi hingga empuk, potong dadu.\r\n2.Haluskan bawang merah, bawang putih, dan keluwak.\r\n3.Tumis bumbu halus dengan lengkuas, serai, daun jeruk, dan daun salam hingga harum.\r\n4.Masukkan daging sapi, tambahkan air kaldu, garam, dan gula.\r\n5.Masak hingga bumbu meresap dan kuah menghitam.\r\n6.Sajikan rawon dengan nasi, tauge, dan sambal.', 'img/resepku/1716810586.jpeg', 1, 0, '2024-05-27 11:49:46', '2024-05-27 11:49:46'),
(53, 'Rujak Cingur', 'Jawa Timur', '-Cingur sapi\r\n-Tempe\r\n-Tahu\r\n-Kangkung\r\n-Tauge\r\n-Kacang panjang\r\n-Lontong\r\n-Petis\r\n-Gula merah\r\n-Garam\r\n-Kacang tanah\r\n-Cabai', '1.Rebus cingur sapi hingga empuk, potong-potong.\r\n2.Goreng tempe dan tahu, potong dadu.\r\n3.Rebus kangkung, tauge, dan kacang panjang.\r\n4.Haluskan petis, gula merah, garam, kacang tanah, dan cabai.\r\n5.Campur semua bahan dengan bumbu petis.\r\n6.Sajikan rujak cingur dengan lontong.', 'img/resepku/1716810623.jpeg', 1, 0, '2024-05-27 11:50:23', '2024-05-27 11:50:23'),
(54, 'Soto Lamongan', 'Jawa Timur', '-Daging ayam\r\n-Bawang merah\r\n-Bawang putih\r\n-Kemiri\r\n-Serai\r\n-Daun salam\r\n-Daun jeruk\r\n-Santan\r\n-Garam\r\n-Merica', '1.Rebus ayam hingga matang, suwir dagingnya.\r\n2.Haluskan bawang merah, bawang putih, dan kemiri.\r\n3.Tumis bumbu halus dengan serai, daun salam, dan daun jeruk hingga harum.\r\n4.Masukkan santan, garam, dan merica, masak hingga mendidih.\r\n5.Tambahkan ayam suwir, masak hingga bumbu meresap.\r\n6.Sajikan soto lamongan dengan pelengkap seperti lontong, telur rebus, dan sambal.', 'img/resepku/1716810676.jpeg', 1, 0, '2024-05-27 11:51:16', '2024-05-27 11:51:16'),
(55, 'Pecel Madiun', 'Jawa Timur', '-Sayuran kacang panjang\r\n- bayam, tauge\r\n-Bumbu pecel \r\nterdiri dari:\r\n-kacang tanah\r\n-cabai\r\n-gula merah\r\n-garam\r\n-kencur\r\n- daun jeruk\r\n-Lontong', '1.Rebus sayuran hingga matang.\r\n2.Haluskan kacang tanah, cabai, gula merah, garam, kencur, dan daun jeruk.\r\n3.Campur bumbu halus dengan air, aduk rata.\r\n4.Sajikan sayuran dengan lontong dan bumbu pecel.', 'img/resepku/1716810767.jpeg', 1, 0, '2024-05-27 11:52:47', '2024-05-27 11:52:47'),
(56, 'Nasi Krawu Gresik', 'Jawa Timur', '-Nasi\r\n-Daging sapi suwir\r\n-Sambal terasi\r\n-Serundeng', '1.Tumis daging sapi suwir dengan bumbu hingga meresap.\r\n2.Sajikan nasi dengan daging sapi suwir, sambal terasi, dan serundeng.', 'img/resepku/1716810820.jpeg', 1, 0, '2024-05-27 11:53:40', '2024-05-27 11:53:40'),
(57, 'Sate Ponorogo', 'Jawa Timur', '-Daging ayam\r\n-Bawang merah\r\n-Bawang putih\r\n-Ketumbar\r\n-Kecap manis\r\n-Garam', '1.Potong daging ayam menjadi dadu.\r\n2.Haluskan bawang merah, bawang putih, dan ketumbar.\r\n3.Lumuri daging dengan bumbu halus dan garam, diamkan selama 1 jam.\r\n4.Tusuk daging dengan tusuk sate, bakar hingga matang.\r\n5.Sajikan dengan kecap manis.', 'img/resepku/1716810863.jpeg', 1, 0, '2024-05-27 11:54:23', '2024-05-27 11:54:23'),
(58, 'Bebek Sinjay', 'Jawa Timur', '-Bebek\r\n-Bawang merah\r\n-Bawang putih\r\n-Kunyit\r\n-Jahe\r\n-Serai\r\n-Daun salam\r\n-Garam', '1.Potong bebek menjadi bagian besar.\r\n2.Haluskan bawang merah, bawang putih, kunyit, dan jahe.\r\n3.Tumis bumbu halus dengan serai dan daun salam hingga harum.\r\n4.Masukkan bebek, tambahkan air, garam, dan gula.\r\n5.Masak hingga bebek empuk dan bumbu meresap.\r\n6.Sajikan bebek sinjay dengan nasi hangat dan sambal.', 'img/resepku/1716810900.jpeg', 1, 0, '2024-05-27 11:55:00', '2024-05-27 11:55:00'),
(59, 'Nasi Tumpang Kediri', 'Jawa Timur', '-Tempe bosok\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabai merah\r\n-Lengkuas\r\n-Daun salam\r\n-Gula merah\r\n-Garam', '1.Haluskan tempe bosok, bawang merah, bawang putih, dan cabai merah.\r\n2.Tumis bumbu halus dengan lengkuas dan daun salam hingga harum.\r\n3.Tambahkan santan, gula merah, dan garam, masak hingga mendidih.\r\n4.Sajikan nasi tumpang dengan sayuran rebus dan sambal.', 'img/resepku/1716810936.jpeg', 1, 0, '2024-05-27 11:55:36', '2024-05-27 11:55:36'),
(60, 'Tahu Campur Lamongan', 'Jawa Timur', '-Tahu goreng\r\n-Lontong\r\n-Mie kuning\r\n-Lentho\r\n-Tauge\r\n-Selada\r\n-Kuah petis', '1.Potong tahu goreng dan lontong.\r\n2.Rebus mie kuning dan tauge hingga matang.\r\n3.Susun tahu, lontong, mie, lentho, tauge, dan selada di piring.\r\n4.Siram dengan kuah petis, sajikan tahu campur selagi hangat.', 'img/resepku/1716810974.jpeg', 1, 0, '2024-05-27 11:56:15', '2024-05-27 11:56:15'),
(61, 'Lontong Balap', 'Jawa Timur', '-Lontong\r\n-Tahu goreng\r\n-Tauge\r\n-Lentho\r\n-Bawang goreng\r\n-Sambal petis\r\n-Kecap manis', '1.Potong lontong dan tahu goreng.\r\n2.Rebus tauge hingga matang.\r\n3.Susun lontong, tahu, tauge, dan lentho di piring.\r\n4.Tambahkan bawang goreng, sambal petis, dan kecap manis.\r\n5.Sajikan lontong balap selagi hangat.', 'img/resepku/1716811082.jpeg', 1, 0, '2024-05-27 11:58:02', '2024-05-27 11:58:02'),
(62, 'Angsle', 'Banten', '-Kacang hijau\r\n-Roti tawar\r\n-Santan\r\n-Jahe\r\n-Daun pandan\r\n-Gula merah\r\n-Garam\r\n-Air', '1.Rebus kacang hijau hingga empuk, tiriskan.\r\n2.Rebus santan, jahe, daun pandan, gula merah, dan garam hingga mendidih.\r\n3.Tambahkan kacang hijau, masak sebentar.\r\n4.Sajikan angsle dengan roti tawar potong dan taburan kelapa parut.', 'img/resepku/1716860218.jpeg', 1, 0, '2024-05-28 01:36:58', '2024-05-28 01:36:58'),
(63, 'Sayur Besan', 'Banten', '-Labu siam\r\n-Kacang panjang\r\n-Tahu\r\n-Tempe\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabai merah\r\n-Lengkuas\r\n-Daun salam\r\n-Serai\r\n-Garam\r\nGula merah', '1.Potong labu siam, kacang panjang, tahu, dan tempe.\r\n2.Tumis bumbu halus (bawang merah, bawang putih, cabai merah) hingga harum.\r\n3.Masukkan lengkuas, daun salam, dan serai, aduk rata.\r\n4.Tambahkan sayuran, tahu, dan tempe, aduk hingga rata.\r\n5.Tuang santan, masak hingga sayuran matang.\r\n6.Sajikan sayur besan dengan lontong.', 'img/resepku/1716860305.jpeg', 1, 0, '2024-05-28 01:38:25', '2024-05-28 01:38:25'),
(64, 'Ikan Cue', 'Banten', '-Ikan cue\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabai merah\r\n-Tomat\r\n-Kecap manis\r\n-Garam\r\n-Gula', '1.Tumis bawang merah, bawang putih, dan cabai merah hingga harum.\r\n2.Masukkan tomat, kencur, garam, dan gula merah.\r\n3.Tambahkan ikan cue, masak hingga bumbu meresap.\r\n4.Sajikan ikan cue dengan nasi hangat.', 'img/resepku/1716860971.jpeg', 1, 0, '2024-05-28 01:49:31', '2024-05-28 01:49:31'),
(65, 'Bakso Bakar', 'Banten', '-Daging sapi giling\r\n-Tepung tapioka\r\n-Bawang merah\r\n-Bawang putih\r\n-Merica\r\n-Garam\r\n-Gula\r\n-Kecap manis\r\n-Tusukan sate', '1.Campur daging sapi giling, tepung tapioka, bawang merah, bawang putih, merica, dan garam.\r\n2.Bentuk adonan menjadi bulatan kecil.\r\n3.Rebus bakso hingga matang, angkat dan tiriskan.\r\n4.Tusuk bakso dengan tusukan sate.\r\n5.Olesi bakso dengan kecap manis, lalu bakar hingga kecokelatan.\r\n6.Sajikan bakso bakar dengan saus sambal.', 'img/resepku/1716861106.jpeg', 1, 0, '2024-05-28 01:51:46', '2024-05-28 01:51:46'),
(66, 'Tauge Goreng', 'Banten', '-Tauge\r\n-Tahu\r\n-Oncom\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabai merah\r\n-Kecap manis\r\n-Garam\r\nGula merah', '1.Tumis bawang merah, bawang putih, dan cabai merah hingga harum.\r\n2.Masukkan tahu dan oncom yang telah dipotong kecil, aduk rata.\r\n3.Tambahkan kecap manis, garam, dan gula merah, aduk hingga rata.\r\n4.Masukkan tauge, aduk sebentar hingga layu.\r\n5.Sajikan tauge goreng dengan lontong dan sambal kacang.', 'img/resepku/1716862362.jpeg', 1, 0, '2024-05-28 02:12:42', '2024-05-28 02:12:42'),
(67, 'Gurame Bakar', 'Banten', '-Ikan gurame\r\n-Bawang merah\r\n-Bawang putih\r\n-Ketumbar\r\n-Kemiri\r\n-Kunyit\r\n-Serai\r\n-Daun salam\r\n-Kecap manis\r\n-Garam\r\n-Gula merah', '1.Bersihkan ikan gurame, lumuri dengan bumbu halus (bawang merah, bawang putih, ketumbar, kemiri, kunyit, garam).\r\n2.Panggang ikan gurame hingga matang dan kecokelatan.\r\n3.Sajikan gurame bakar dengan sambal kecap dan lalapan.', 'img/resepku/1716870292.jpeg', 1, 0, '2024-05-28 04:24:52', '2024-05-28 04:24:52'),
(68, 'Ayam Goreng Serang', 'Banten', '-Ayam kampung\r\n-Bawang merah\r\n-Bawang putih\r\n-Ketumbar\r\n-Kemiri\r\n-Kunyit\r\n-Serai\r\n-Daun salam\r\n-Garam\r\n-Gula', '1.Lumuri ayam dengan bumbu halus (bawang merah, bawang putih, ketumbar, kemiri, kunyit, garam).\r\n2.Diamkan ayam selama 30 menit agar bumbu meresap.\r\n3.Goreng ayam hingga matang dan kecokelatan.\r\n4.Sajikan ayam goreng dengan sambal dan lalapan.', 'img/resepku/1716871553.jpeg', 1, 0, '2024-05-28 04:45:53', '2024-05-28 04:45:53'),
(69, 'Bandeng Pecak', 'Banten', '-Ikan bandeng\r\n-Bawang merah\r\n-Bawang putih\r\n-Cabai merah\r\n-Tomat\r\n-Kencur\r\n-Garam\r\n-Gula merah\r\n-Air jeruk nipis', '1.Bersihkan ikan bandeng, lumuri dengan air jeruk nipis dan garam.\r\n2.Goreng ikan bandeng hingga matang, angkat dan tiriskan.\r\n3.Tumis bawang merah, bawang putih, cabai merah, dan tomat hingga harum.\r\n4.Tambahkan kencur, garam, dan gula merah, aduk rata.\r\n5.Siramkan bumbu pecak di atas ikan bandeng goreng.\r\n6.Sajikan bandeng pecak dengan nasi putih.', 'img/resepku/1716871738.jpeg', 1, 0, '2024-05-28 04:48:58', '2024-05-28 04:48:58'),
(70, 'Liwet Serang', 'Banten', '-Beras\r\n-Ikan teri\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Lengkuas\r\n-Daun salam\r\n-Serai\r\n-Garam\r\n-Gula', '1.Cuci bersih beras, rendam selama 30 menit.\r\n2.Tumis bawang merah, bawang putih, dan lengkuas hingga harum.\r\n3.Masukkan ikan teri, aduk rata.\r\n4.Tambahkan beras, aduk hingga tercampur.\r\n5.Tuang santan, tambahkan daun salam dan serai.\r\n6.Masak nasi hingga matang dan santan meresap.\r\n7.Sajikan nasi liwet dengan lauk pendamping.', 'img/resepku/1716871817.jpeg', 1, 0, '2024-05-28 04:50:17', '2024-05-28 04:50:17'),
(71, 'Sop Ikan Tangkil', 'Banten', '-Ikan (tenggiri atau kakap)\r\n-Bawang merah\r\n-Bawang putih\r\n-Tomat\r\n-Daun bawang\r\n-Seledri\r\n-Jahe\r\n-Garam\r\n-Gula\r\n-Air jeruk nipis', '1.Bersihkan ikan (tenggiri atau kakap), potong sesuai selera.\r\n2.Tumis bawang merah, bawang putih, jahe hingga harum.\r\n3.Tambahkan tomat, daun bawang, dan seledri, aduk rata.\r\n4.Masukkan ikan, tambahkan garam dan gula, aduk hingga rata.\r\n5.Tambahkan air dan air jeruk nipis, masak hingga ikan matang.\r\n6.Sajikan sop ikan tangkil dengan nasi hangat.', 'img/resepku/1716871933.jpeg', 1, 0, '2024-05-28 04:52:13', '2024-05-28 04:52:13'),
(72, 'Cireng', 'Jawa Barat', '-Tepung tapioka\r\n-Bawang putih\r\n-Garam\r\n-Air\r\n-Minyak goreng\r\n-Sambal rujak (untuk cocolan)', '1.Campurkan tepung tapioka dengan bawang putih halus dan garam.\r\n2.Tambahkan air sedikit demi sedikit hingga adonan bisa dipulung.\r\n3.Bentuk adonan menjadi bulat pipih.\r\n4.Goreng cireng dalam minyak panas hingga kecokelatan.\r\n5.Sajikan cireng dengan sambal rujak.', 'img/resepku/1717002897.jpg', 1, 0, '2024-05-29 17:14:57', '2024-05-29 17:14:57'),
(73, 'Es Cendol', 'Jawa Barat', '-Tepung hunkwe\r\n-Air\r\n-Pandan (untuk pewarna hijau)\r\n-Gula merah\r\n-Santan\r\n-Garam\r\n-Es batu', '1.Campurkan tepung hunkwe dengan air dan pewarna hijau dari pandan.\r\n2.Masak hingga adonan kental dan matang.\r\n3.Cetak adonan dengan alat pencetak cendol, masukkan ke dalam air dingin.\r\n4.Rebus gula merah dengan air hingga larut dan mengental.\r\n5.Rebus santan dengan garam hingga mendidih.\r\n6.Sajikan cendol dengan gula merah, santan, dan es batu.', 'img/resepku/1717003685.jpg', 1, 0, '2024-05-29 17:28:05', '2024-05-29 17:28:05'),
(74, 'Nasi Liwet Sunda', 'Jawa Barat', '-Beras\r\n-Santan\r\n-Daun salam\r\n-Serai\r\n-Garam\r\n-Ikan teri', '1.Cuci beras hingga bersih.\r\n2.Rebus santan dengan daun salam, serai, dan garam hingga mendidih.\r\n3.Masukkan beras ke dalam santan, masak hingga santan terserap.\r\n4.Kukus nasi hingga matang.\r\n5.Sajikan nasi liwet dengan ikan teri goreng.', 'img/resepku/1717003737.jpg', 1, 0, '2024-05-29 17:28:57', '2024-05-29 17:28:57'),
(75, 'Tahu Sumedang', 'Jawa Barat', '-Tahu putih\r\n-Garam\r\n-Bawang putih\r\n-Air\r\n-Minyak goreng', '1.Campurkan air dengan garam dan bawang putih halus.\r\n2.Rendam tahu dalam larutan garam selama beberapa menit.\r\n3.Goreng tahu hingga kecokelatan.\r\n4.Sajikan tahu Sumedang hangat.', 'img/resepku/1717003789.jpeg', 1, 0, '2024-05-29 17:29:49', '2024-05-29 17:29:49'),
(76, 'Empal Gentong', 'Jawa Barat', '-Daging sapi\r\n-Santan\r\n-Bawang merah\r\n-Bawang putih\r\n-Jahe\r\n-Kunyit\r\n-Lengkuas\r\n-Serai\r\n-Daun salam\r\n-Garam\r\n-Merica\r\n-Kayu manis\r\n-Cengkeh\r\n-Kapulaga\r\n-Kaldu sapi', '1.Tumis bawang merah, bawang putih, jahe, kunyit, lengkuas, dan serai hingga harum.\r\n2.Masukkan daging sapi dan tumis hingga berubah warna.\r\n3.Tambahkan air dan kaldu sapi, masak hingga daging empuk.\r\n4.Tambahkan santan, kayu manis, cengkeh, kapulaga, garam, dan 5.merica. Masak hingga bumbu meresap.\r\n5.Sajikan empal gentong dengan nasi atau lontong.', 'img/resepku/1717003862.jpg', 1, 0, '2024-05-29 17:31:02', '2024-05-29 17:31:02'),
(77, 'Asinan Bogor', 'Jawa Barat', '-Kol\r\n-Tauge\r\n-Timun\r\n-Wortel\r\n-Tahu putih\r\n-Kacang tanah goreng\r\n-Cuka\r\n-Cabe merah\r\n-Bawang putih\r\n-Garam\r\n-Gula\r\n-Air', '1.Potong semua sayuran dan tahu putih.\r\n2.Rebus cabe merah dan bawang putih, haluskan.\r\n3.Campurkan bumbu halus dengan cuka, garam, gula, dan air. Aduk rata.\r\n4.Siram bumbu asinan ke sayuran dan tahu.\r\n5.Sajikan dengan taburan kacang tanah goreng.', 'img/resepku/1717004619.jpeg', 1, 0, '2024-05-29 17:43:39', '2024-05-29 17:43:39'),
(78, 'Doclang', 'Jawa Barat', '-Lontong\r\n-Kentang\r\n-Tahu\r\n-Telur rebus\r\n-Bumbu kacang \r\nterdiri dari :\r\n-kacang tanah\r\n-cabe merah\r\n-bawang putih\r\n- gula merah\r\n-garam\r\n-air \r\n-asam jawa\r\n-Kecap manis', '1.Potong semua sayuran dan tahu putih.\r\n2.Rebus cabe merah dan bawang putih, haluskan.\r\n3.Campurkan bumbu halus dengan cuka, garam, gula, dan air. Aduk rata.\r\n4.Siram bumbu asinan ke sayuran dan tahu.\r\n5.Sajikan dengan taburan kacang tanah goreng.', 'img/resepku/1717004724.jpg', 1, 0, '2024-05-29 17:45:24', '2024-05-29 17:45:24'),
(79, 'Sate Maranggi', 'Jawa Barat', '-Daging sapi\r\n-Kecap manis\r\n-Bawang putih\r\n-Bawang merah\r\n-Ketumbar\r\n-Garam\r\n-Merica\r\n-Gula merah\r\n-Air asam jawa', '1.Haluskan bawang putih, bawang merah, ketumbar, garam, dan merica.\r\n2.Campurkan bumbu halus dengan kecap manis, gula merah, dan air asam jawa.\r\n3.Rendam daging sapi dalam bumbu selama beberapa jam.\r\n4.Tusuk daging sapi dengan tusuk sate.\r\n5.Bakar sate hingga matang dan kecokelatan.\r\n6.Sajikan sate maranggi dengan nasi atau lontong.', 'img/resepku/1717004763.jpg', 1, 0, '2024-05-29 17:46:03', '2024-05-29 17:46:03'),
(80, 'Gemblong', 'Jawa Barat', '-Tepung ketan\r\n-Kelapa parut\r\n-Garam\r\n-Santan\r\n-Gula merah\r\n-Minyak goreng', '1.Campurkan tepung ketan, kelapa parut, garam, dan santan hingga menjadi adonan yang bisa dipulung.\r\n2.Bentuk adonan menjadi bulat pipih.\r\n3.Goreng gemblong dalam minyak panas hingga kecokelatan.\r\n4.Rebus gula merah dengan sedikit air hingga larut dan mengental.\r\n5.Celupkan gemblong yang sudah digoreng ke dalam larutan gula merah.\r\n6.Biarkan gemblong mengering sebelum disajikan.', 'img/resepku/1717004798.jpg', 1, 0, '2024-05-29 17:46:38', '2024-05-29 17:46:38'),
(81, 'Opak', 'Jawa Barat', '-Tepung beras\r\n-Kelapa parut\r\n-Garam\r\n-Air', '1.Campurkan tepung beras, kelapa parut, garam, dan air hingga menjadi adonan yang kental.\r\n2.Ambil sedikit adonan, pipihkan di atas daun pisang atau plastik.\r\n3.Jemur opak hingga kering.\r\n4.Panggang opak di atas bara api atau wajan panas hingga matang.\r\n5.Sajikan opak sebagai camilan atau pendamping makanan.', 'img/resepku/1717004841.jpg', 1, 0, '2024-05-29 17:47:21', '2024-06-16 14:58:01');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;